#!/usr/bin/env bash
set -e

git checkout master 2>/dev/null
TAG=`git describe --abbrev=0 --tags`
echo "Checking out latest version" $TAG
git checkout $TAG 2>/dev/null

echo "Building distribution"
npm run-script build
mkdir -p tmp
cp license.js tmp/sparqljs-browser.js
browserify -s sparqljs sparql.js >> tmp/sparqljs-browser.js
uglifyjs --compress --mangle --comments -- tmp/sparqljs-browser.js > tmp/sparqljs-browser.min.js 2>/dev/null

echo "Committing distribution"
git checkout dist
mv tmp/sparqljs-browser.js tmp/sparqljs-browser.min.js .
git add sparqljs-browser.js sparqljs-browser.min.js
git commit -n -m "Release $TAG."
git push

git checkout master 2>/dev/null
rmdir tmp
