BASE <ex:>
SELECT * WHERE {
  <s1> <p1> <o1>;
    <p2> <o2>;
    <p3> [
      <p4> <o4>;
      <p5> [
        <p6> <o6>;
        <p7> <o7>, <o7a>
      ];
      <p8> <o8>
    ];
    <p9> <o9>, <o9a>, <o9b>.
}
