PREFIX dbpedia-owl:<http://dbpedia.org/owl/#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
SELECT ?movie
WHERE {
  ?movie a dbpedia-owl:Film ;
    dbpedia-owl:starring [
      rdfs:label "Brad Pitt"@en ;
      ^dbpedia-owl:starring ?otherMovie
    ] .
}
