CREATE SILENT GRAPH <ex:graph>;
CREATE GRAPH <ex:graph>;
CLEAR SILENT GRAPH <ex:graph>;
CLEAR GRAPH <ex:graph>;
CLEAR DEFAULT;
CLEAR NAMED;
CLEAR ALL;
DROP SILENT GRAPH <ex:graph>;
DROP GRAPH <ex:graph>;
DROP DEFAULT;
DROP NAMED;
DROP ALL;
