PREFIX ex: <http://example.com/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT (<<GRAPH ex:g {ex:Moscow a <<GRAPH ex:g {ex:Moscow a ex:City}>>}>> as ?moscow) WHERE {
    << GRAPH ex:graph {<< GRAPH ex:graph {ex:Moscow a ex:City} >> a ex:City} >> ex:author ?person .
    BIND(<< GRAPH ex:g {<< GRAPH ex:g {ex:SaintPetersburg a ex:City} >> a ex:City} >> as ?spb)
}
