PREFIX ex: <http://example.com/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT * WHERE {
    VALUES ?x {
        << ex:SaintPetersburg a ex:City >>
        << ex:a ex:b << ex:Moscow a ex:City >> >>
    }
}
