PREFIX ex: <http://example.com/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT * WHERE {
    <<GRAPH ?g {?s ?p ?o}>> ex:author ex:Bob .
    << GRAPH ex:graph {ex:Moscow a ex:City} >> ex:author ?person .
    << GRAPH ex:g2 { _:b ex:x () }>> ex:broken true .
}
