PREFIX ex: <http://example.com/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT (<<GRAPH ex:g {ex:Moscow a <<GRAPH ex:g {ex:Moscow a ex:City}>>}>> as ?moscow) WHERE {
    ex:a ex:name ex:c
}
